<?php
/** @var $block \Magento\Framework\View\Element\Template */
?>

<form id="delete-account-form">
    <div id="delete-account-section">
        <input class="checkbox-custom" type="checkbox" name="delete_account" value="1">
        <span>Request Account Information Deletion</span>
        <div>
            <button type="button" id="delete-account-submit" class="btn-submit">Submit</button>
        </div>
    </div>
    <div id="notification"></div>
</form>
